//@ts-nocheck
import React, { createContext, useContext, useState, useEffect } from 'react';
import type { Language } from '../types/language';
import { canUseFunctional } from '../utils/cookieConsent';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Переводы
const translations = {
  ru: {
    // Общие
    'welcome': 'Добро пожаловать',
    'home': 'Главная',
    'about': 'О предприятии',
    'news': 'Новости',
    'activity': 'Услуги',
    'air_navigation': 'Аэронавигационная информация',
    'services': 'Услуги',
    'contacts': 'Контакты',
    'search': 'Поиск',
    'login': 'Войти',
    'logout': 'Выйти',
    'admin_panel': 'Панель администратора',
    'useful_links': 'Полезные ссылки',
    'cookie_policy': 'Политика использования cookie',
    'company_name_short': 'РУП «Белаэронавигация»',
    'all_rights_reserved': 'Все права защищены',
    
    // О предприятии
    'about_company': 'О предприятии',
    'about_company_default_subtitle': 'Информация о нашем предприятии, его структуре, целях и принципах работы в сфере аэронавигационного обслуживания воздушного движения.',
    'about_company_placeholder': 'Здесь будет размещена информация о нашем предприятии, его истории, структуре и деятельности.',
    'manage_content': 'Управление контентом',
    'manage_about_company_content': 'Управление контентом страницы о предприятии',
    'edit_about_company_content_description': 'Редактируйте заголовок, подзаголовок и основной контент страницы о предприятии.',
    'page_title': 'Заголовок страницы',
    'subtitle': 'Подзаголовок',
    'company_description_placeholder': 'Краткое описание предприятия...',
    'main_content': 'Основной контент',
    'add_content': 'Добавить контент',
    'content_updated_successfully': 'Контент страницы успешно обновлен',
    'error_saving_content': 'Ошибка при сохранении контента',
    'saving': 'Сохранение...',
    'edit_page_content_description': 'Редактируйте заголовок, подзаголовок и основной контент страницы на трех языках.',
    'subtitle_placeholder': 'Краткое описание...',
    'save_changes': 'Сохранить изменения',
    'cancel': 'Отмена',
    'management': 'Руководство',
    'structure': 'Структура предприятия',
    'branches': 'Наши филиалы',
    'security_policy': 'Политика безопасности',
    'history': 'История',
    'vacancies': 'Открытые вакансии',
    'go': 'Перейти',
    'categories_not_found': 'Категории не найдены',
    'error_loading_data': 'Не удалось загрузить данные',
    'download': 'Скачать',
    'unknown_file': 'Неизвестный файл',
    'column': 'Колонка',
    
    // Филиалы
    'loading_branches': 'Загрузка информации о филиалах...',
    'error_loading_branches': 'Ошибка загрузки данных о филиалах.',
    'please_try_again_later': 'Пожалуйста, попробуйте еще раз позже.',
    'structural_units': 'Структурные подразделения',
    'branches_not_found': 'Филиалы не найдены',
    'data_will_be_added_soon': 'Данные будут добавлены в ближайшее время',
    'invalid_branch_id': 'Неверный идентификатор филиала',
    'loading_branch': 'Загрузка информации о филиале...',
    'error_loading_branch': 'Не удалось загрузить данные о филиале',
    'back_to_list': 'Назад к списку',
    'contact_phones': 'Контактные телефоны:',
    'description': 'Описание',
    'additional_information': 'Дополнительная информация',
    'error_loading_content': 'Ошибка загрузки контента',
    'location_on_map': 'Расположение на карте',
    'address_not_specified': 'Адрес не указан',
    'address_required_for_map': 'Для отображения карты необходимо указать адрес',
    'additional_photos': 'Дополнительные фото',
    'image': 'Изображение',
    'branches_not_available': 'Филиалы недоступны',
    
    // Добровольное сообщение
    'voluntary_report_title': 'ДОБРОВОЛЬНОЕ СООБЩЕНИЕ О НЕБЕЗОПАСНОМ СОБЫТИИ',
    'voluntary_report_description': 'Информация, включаемая в данное сообщение, служит исключительно целям повышения безопасности полетов. Ф.И.О составителя сообщения можно не указывать. Если имя, должность, контактные данные составителя указываются, то они НЕ БУДУТ СОХРАНЯТЬСЯ, после проверки поступившей информации. Ни при каких обстоятельствах личность составителя не будет раскрыта или сообщена другому должностному лицу предприятия или иной организации.',
    'voluntary_report_warning': 'Если имя и должность указываются, то после рассмотрения они будут исключены из сообщения.',
    'compiler_information': 'Информация о составителе',
    'full_name': 'Ф.И.О.',
    'enter_full_name': 'Введите Ф.И.О.',
    'organization_position_contacts': 'Организация/должность, контактные данные',
    'enter_organization_position_contacts': 'Введите организацию/должность, контактные данные',
    'event_information': 'Информация о событии',
    'event_date': 'Дата события',
    'event_time': 'Время события',
    'event_location': 'Место события',
    'enter_event_location': 'Введите место события',
    'event_description': 'Описание события',
    'describe_event_in_detail': 'Подробно опишите событие',
    'compilation_date': 'Дата составления информации о событии',
    'compilation_time': 'Время составления информации о событии',
    'recurrence_probability': 'Вероятность повторения подобного события?',
    'event_consequences': 'Каковы будут последствия события, если оно повторится?',
    'select_option': 'Выберите вариант',
    'very_high': 'Очень высокая',
    'high': 'Высокая',
    'medium': 'Средняя',
    'low': 'Низкая',
    'very_low': 'Очень низкая',
    'unknown': 'Неизвестно',
    'catastrophic': 'Катастрофические',
    'critical': 'Критические',
    'significant': 'Значительные',
    'minor': 'Незначительные',
    'minimal': 'Минимальные',
    'sending': 'Отправка...',
    'send_message': 'ОТПРАВИТЬ СООБЩЕНИЕ',
    'voluntary_report_sent_successfully': 'Сообщение успешно отправлено',
    'error_sending_voluntary_report': 'Ошибка при отправке сообщения',
    
    // Анкета потребителя
    'consumer_questionnaire_title': 'Анкета потребителя аэронавигационных услуг Республики Беларусь',
    'dear_colleagues': 'Уважаемые Коллеги!',
    'questionnaire_intro_1': 'Благодарим Вас за сотрудничество с Государственным предприятием БЕЛАЭРОНАВИГАЦИЯ. Ваше мнение о качестве предоставляемых аэронавигационных услуг имеет для нас большое значение и поможет нам улучшить качество обслуживания.',
    'questionnaire_intro_2': 'Просим Вас ответить на вопросы, представленные ниже.',
    'user_information': 'ИНФОРМАЦИЯ О ПОЛЬЗОВАТЕЛЕ',
    'user_address': 'Адресс пользователя',
    'user_name': 'Наименование пользователя',
    'satisfaction_with_service': 'УДОВЛЕТВОРЕННОСТЬ ОКАЗЫВАЕМОЙ АЭРОНАВИГАЦИОННОЙ УСЛУГОЙ',
    'satisfaction_5': '5 баллов - высокая степень удовлетворенности',
    'satisfaction_4': '4 балла - хорошая степень удовлетворенности',
    'satisfaction_3': '3 балла - средняя степень удовлетворенности',
    'satisfaction_2': '2 балла - низкая степень удовлетворенности',
    'satisfaction_1': '1 балл - полная неудовлетворенность',
    'phraseology_quality': 'Качество ведения фразеологии радиообмена авиационным персоналом',
    'information_timeliness': 'Своевременность информирования о воздушной обстановке',
    'equipment_quality': 'Качество работы радиотехнических средств',
    'procedures_quality': 'Качество процедур обслуживания воздушного движения',
    'select_rating': 'Выберите оценку',
    'satisfaction_reasons': 'Поясните причины снижения оценки удовлетворенности',
    'describe_satisfaction_reasons': 'Опишите причины снижения оценки...',
    'suggestions_for_improvement': 'Ваши замечания, пожелания и предложения по улучшению качества аэронавигационных услуг нашим предприятием',
    'your_suggestions': 'Ваши предложения по улучшению...',
    'completion_date': 'Дата заполнения',
    'enter_antispam_code': 'Введите антиспам код',
    'refresh': 'Обновить',
    'sending_uppercase': 'ОТПРАВКА...',
    'submit': 'ОТПРАВИТЬ',
    'required_fields_note': '* - поля, обязательные для заполнения',
    'questionnaire_sent_successfully': 'Анкета успешно отправлена!',
    'error_sending_questionnaire': 'Ошибка при отправке анкеты',
    'invalid_security_code': 'Неверный код безопасности',
    
    // ELT формы
    'elt_registration_application': 'ЗАЯВЛЕНИЕ О РЕГИСТРАЦИИ ELT',
    'elt_deregistration_application': 'ЗАЯВЛЕНИЕ О СНЯТИИ С РЕГИСТРАЦИИ ELT',
    'elt_registration_basis': 'ОСНОВАНИЕ ДЛЯ РЕГИСТРАЦИИ ELT',
    'elt_registration': 'регистрация ELT',
    'elt_reregistration': 'перерегистрация ELT',
    'elt_information': 'ИНФОРМАЦИЯ ПО ELT',
    'elt_15_digit_code': '15-ЗНАЧНЫЙ ШЕСТНАДЦАТЕРИЧНЫЙ КОД ПОСЫЛКИ',
    'model': 'Модель',
    'serial_number': 'Заводской номер',
    'manufacturer': 'Изготовитель',
    'aircraft_information': 'ИНФОРМАЦИЯ О ВОЗДУШНОМ СУДНЕ',
    'aircraft_type': 'Тип воздушного судна',
    'aircraft_model': 'Модель воздушного судна',
    'aircraft_registration': 'Регистрационный знак воздушного судна',
    'max_people_on_board': 'Максимальное число людей на борту (экипаж и пассажиры)',
    'operator_information': 'ИНФОРМАЦИЯ ОБ ЭКСПЛУАТАНТЕ ВОЗДУШНОГО СУДНА',
    'aircraft_operator': 'Эксплуатант воздушного судна',
    'mailing_address': 'Почтовый адрес',
    'work_phone': 'Рабочий телефон',
    'mobile_phone': 'Мобильный телефон',
    'error_sending_form': 'Ошибка при отправке формы',
    'emergency_contact_data': 'ДАННЫЕ ДЛЯ СВЯЗИ В СЛУЧАЕ БЕДСТВИЯ',
    'responsible_person_data': 'ДАННЫЕ ОТВЕТСТВЕННОГО ЗА РЕГИСТРАЦИЮ',
    'responsible_person': 'Ответственное лицо',
    'billing_details': 'РЕКВИЗИТЫ ДЛЯ ВЫСТАВЛЕНИЯ СЧЁТА',
    'full_organization_name': 'Полное название организации',
    'short_organization_name': 'Сокращенное название организации',
    'legal_address': 'Место нахождения (юридический адрес)',
    'unp': 'УНП',
    'date': 'Дата',
    'signature': 'Подпись',
    'submit_application': 'ОТПРАВИТЬ ЗАЯВЛЕНИЕ',
    'responsible_person_deregistration_data': 'ДАННЫЕ ОТВЕТСТВЕННОГО ЗА СНЯТИЕ С РЕГИСТРАЦИИ ELT',
    'document_not_found': 'Документ не найден',
    'instruction_document_not_found': 'Документ инструкции не найден',
    
    // Новости
    'all_news': 'Все новости',
    'back_to_news': 'Назад к новостям',
    'published_by_admin': 'Опубликовано администратором',
    'published': 'Опубликовано',
    'details': 'Подробнее',
    'apply': 'Откликнуться',
    'send_resume': 'Отправить резюме',
    'no_vacancies_available': 'Нет доступных вакансий',
    'no_vacancies_message': 'В настоящее время открытых вакансий нет. Пожалуйста, зайдите позже.',
    'loading_vacancies': 'Загрузка вакансий...',
    'close': 'Закрыть',
    'send_by_email': 'Отправить на почту',
    'description': 'Описание',
    'requirements': 'Требования',
    'work_conditions': 'Условия работы',
    'salary': 'Зарплата',
    'location': 'Местоположение',
    'employment_type': 'Тип занятости',
    'apply_to_vacancy': 'Откликнуться',
    'manage_vacancies_page_content': 'Управление контентом страницы вакансий',
    'open_vacancies': 'Открытые вакансии',
    'join_our_team_placeholder': 'Присоединяйтесь к нашей команде...',
    'why_work_with_us': 'Почему стоит работать с нами?',
    'stability': 'Стабильность',
    'stability_description': 'Работа в крупной государственной организации с гарантированной занятостью',
    'development': 'Развитие',
    'development_description': 'Возможности для профессионального роста и обучения',
    'social_package': 'Социальный пакет',
    'social_package_description': 'Полный социальный пакет и дополнительные льготы',
    'application_for_vacancy': 'Отклик на вакансию',
    'hello': 'Здравствуйте!',
    'resume_attached': 'Резюме прикреплю к письму.',
    'additional_content': 'Дополнительный контент',
    'updated': 'Обновлено',
    'additional_photos': 'Дополнительные фото',
    'company_news': 'Новости предприятия',
    'flight_safety': 'Безопасность полетов',
    'information_security': 'Информационная безопасность',
    'emergency': 'МЧС информирует',
    'police': 'МВД информирует',
    'energy_saving': 'Энергосбережение',
    'loading_categories': 'Загрузка категорий...',
    
    // Деятельность
    'international': 'Международное сотрудничество',
    'standards': 'Стандарты в области аэронавигации',
    'hr_policy': 'Кадровая политика',
    'information_systems': 'Информационные системы',
    'training_center': 'Центр профессиональной подготовки',
    'airport': 'Аэропортовая деятельность',
    'support': 'Обеспечение деятельности предприятия',
    'quality_policy': 'Политика в области качества',
    'anti_corruption': 'Противодействие коррупции',
    'regulations': 'Нормативные документы',
    
    // Аэронавигация
    'aeronautical_information_subtitle': 'Информация о правилах и процедурах аэронавигационного обслуживания воздушного движения.',
    'appeals': 'Обращения',
    'appeals_subtitle': 'Информация о порядке подачи и рассмотрения обращений граждан и юридических лиц.',
    'services_subtitle': 'Информация об услугах предприятия.',
    'page': 'Страница',
    'information': 'Информация',
    'eaip': 'Сборник аэронавигационной информации (EAIP)',
    'eaip_vfr': 'Сборник аэронавигационной информации для визуальных полетов (EAIP VFR)',
    'etod': 'Электронные данные о местности и препятствиях (ETOD)',
    'aip_supplements': 'Дополнения к сборнику аэронавигационной информации (AIP SUP)',
    'notam': 'Уведомления авиационным службам (NOTAM)',
    'aircraft_operations': 'Эксплуатация воздушных судов',
    'air_traffic_services': 'Службы воздушного движения',
    'aeronautical_information': 'Аэронавигационная информация',
    'airspace': 'Воздушное пространство',
    'airports': 'Аэродромы',
    'radio_navigation': 'Радионавигация',
    'weather': 'Метеорология',
    'search_rescue': 'Поиск и спасание',
    'aircraft_accidents': 'Авиационные происшествия',
    
    // Услуги
    'air_navigation_services': 'Аэронавигационное обслуживание',
    'meteorological_services': 'Метеорологическое обслуживание',
    'aeronautical_information_services': 'Аэронавигационное информационное обслуживание',
    'search_rescue_services': 'Службы поиска и спасания',
    'training_services': 'Услуги по подготовке персонала',
    'consulting_services': 'Консультационные услуги',
    'technical_support': 'Техническая поддержка',
    
    // Контакты
    'address': 'Адрес',
    'phone': 'Телефон',
    'email': 'Email',
    'working_hours': 'Время работы',
    'minsk_address': 'г. Минск, ул.  Короткевича, 19',
    'working_time': 'Пн-Пт 8:00-17:00',
    
    // Вакансии
    'vacancy_title': 'Открытые вакансии',
    'vacancy_subtitle': 'Присоединяйтесь к нашей команде профессионалов',
    'apply': 'Откликнуться',
    'details': 'Подробнее',
    'requirements': 'Требования',
    'conditions': 'Условия работы',
    'salary': 'Зарплата',
    'location': 'Местоположение',
    'employment_type': 'Тип занятости',
    
    // Cookie
    'cookie_title': 'Мы используем cookie-файлы',
    'cookie_message': 'Мы используем cookie-файлы для улучшения работы сайта, анализа трафика и персонализации контента.',
    'cookie_policy_link': 'Подробнее',
    'accept_all': 'Принять все',
    'reject': 'Отклонить',
    'settings': 'Настроить',
    'cookies': 'cookie',
    'necessary_cookies': 'Необходимые cookie',
    'necessary_cookies_description': 'Эти файлы необходимы для работы нашего веб-сайта. Без них невозможно предоставить запрашиваемые вами услуги.',
    'functional_cookies': 'Функциональные cookie',
    'functional_cookies_description': 'Эти файлы позволяют веб-сайту запоминать ваши предпочтения и обеспечивают расширенную функциональность.',
    'analytics_cookies': 'Аналитические cookie',
    'analytics_cookies_description': 'Эти файлы помогают нам понять, как посетители взаимодействуют с нашим веб-сайтом, собирая анонимную информацию.',
    'marketing_cookies': 'Маркетинговые cookie',
    'marketing_cookies_description': 'Эти файлы используются для показа релевантной рекламы и измерения эффективности рекламных кампаний.',
    'save_preferences': 'Сохранить настройки',
    'cookie_policy': 'Политика использования cookie',
    'last_updated': 'Последнее обновление',
    'your_current_cookie_settings': 'Ваши текущие настройки cookie',
    'always_enabled': 'Всегда включены',
    'enabled': 'Включены',
    'disabled': 'Отключены',
    'change_cookie_settings': 'Изменить настройки cookie',
    'what_are_cookies': 'Что такое cookie?',
    'cookies_description': 'Cookie (куки) — это небольшие текстовые файлы, которые веб-сайты сохраняют на вашем устройстве (компьютере, планшете или мобильном телефоне) при посещении. Они помогают веб-сайтам запоминать информацию о вашем визите, что делает последующие посещения более удобными и полезными.',
    'what_types_of_cookies_do_we_use': 'Какие типы cookie мы используем?',
    'examples_of_use': 'Примеры использования:',
    'save_auth_state': 'Сохранение состояния авторизации',
    'remember_cart_items': 'Запоминание товаров в корзине',
    'security_protection': 'Обеспечение безопасности и защита от мошенничества',
    'save_language_preferences': 'Сохранение языковых предпочтений',
    'remember_region_language': 'Запоминание выбранного региона или языка',
    'save_display_settings': 'Сохранение настроек отображения',
    'content_personalization': 'Персонализация контента',
    'improve_user_experience': 'Улучшение пользовательского опыта',
    'count_visitors': 'Подсчет количества посетителей',
    'analyze_popular_pages': 'Анализ наиболее популярных страниц',
    'determine_traffic_sources': 'Определение источников трафика',
    'improve_site_performance': 'Улучшение производительности сайта',
    'we_may_use_services': 'Мы можем использовать сервисы',
    'show_personalized_ads': 'Показ персонализированной рекламы',
    'track_conversions': 'Отслеживание конверсий',
    'retargeting': 'Ретаргетинг',
    'ad_campaign_analytics': 'Аналитика рекламных кампаний',
    'how_to_manage_cookies': 'Как управлять cookie?',
    'manage_cookies_description': 'Вы можете контролировать и/или удалять cookie по своему усмотрению. Вы можете удалить все cookie, которые уже находятся на вашем компьютере, и настроить большинство браузеров так, чтобы они не сохранялись.',
    'browser_management': 'Управление через браузер:',
    'chrome_cookie_path': 'Настройки → Конфиденциальность и безопасность → Файлы cookie',
    'firefox_cookie_path': 'Настройки → Приватность и защита → Файлы cookie',
    'safari_cookie_path': 'Настройки → Конфиденциальность → Файлы cookie',
    'edge_cookie_path': 'Настройки → Файлы cookie и разрешения сайтов',
    'disable_cookies_warning': 'Обратите внимание, что если вы отключите cookie, некоторые функции нашего веб-сайта могут работать некорректно.',
    'cookie_storage_period': 'Срок хранения cookie',
    'we_use_both_cookie_types': 'Мы используем как сессионные, так и постоянные cookie:',
    'session_cookies': 'Сессионные cookie',
    'session_cookies_description': 'временные файлы, которые удаляются при закрытии браузера',
    'persistent_cookies': 'Постоянные cookie',
    'persistent_cookies_description': 'остаются на вашем устройстве до истечения срока действия или удаления вручную (обычно до 12 месяцев)',
    'cookie_policy_questions': 'Если у вас есть вопросы о нашей политике использования cookie, свяжитесь с нами:',
    'organization': 'Организация',
    'company_full_name': 'Республиканское унитарное предприятие по аэронавигационному обслуживанию воздушного движения «Белаэронавигация»',
    'company_address': 'г. Минск, ул. Короткевича, 19',
    'phone': 'Телефон',
    'fax': 'факс',
    'go_back': 'Вернуться назад',
    
    // Админ панель
    'user_management': 'Управление пользователями',
    'role_management': 'Управление ролями',
    'news_management': 'Управление новостями',
    'category_management': 'Управление категориями',
    'branch_management': 'Управление филиалами',
    'vacancy_management': 'Управление вакансиями',
    'management_management': 'Управление руководителями',
    'management_title': 'РУКОВОДСТВО ГОСУДАРСТВЕННОГО ПРЕДПРИЯТИЯ «БЕЛАЭРОНАВИГАЦИЯ»',
    'loading_managers': 'Загрузка информации о руководителях...',
    'no_managers_info': 'Информация о руководителях отсутствует',
    'data_will_be_added': 'Данные будут добавлены в ближайшее время',
    'book_appointment': 'Записаться на прием',
    'hide_booking': 'Скрыть запись',
    'booking_appointment': 'Запись на прием',
    'fill_booking_form': 'Заполните форму для записи на прием к руководителю',
    'selected_time': 'Выбранное время',
    'full_name': 'ФИО',
    'enter_full_name': 'Введите ваше полное имя',
    'enter_email': 'Введите ваш email',
    'additional_info': 'Дополнительная информация',
    'describe_visit_purpose': 'Опишите цель визита (необязательно)',
    'book': 'Записаться',
    'booking_success': 'Запись на прием успешно оформлена!',
    'booking_error': 'Ошибка при записи на прием',
    'fill_required_fields': 'Заполните все обязательные поля',
    'booking_slots': 'Слоты для записи',
    'loading_schedule': 'Загрузка расписания...',
    'booked': 'Занято',
    'unavailable': 'Недоступен',
    'no_available_slots': 'Нет доступных слотов для записи',
    'contact_administrator': 'Обратитесь к администратору для настройки расписания',
    'reception_schedule': 'Расписание приема',
    'offices': 'Кабинеты',
    
    // Дополнительно
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'no_data': 'Нет данных',
    'read_more': 'Читать далее',
    'back': 'Назад',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'edit': 'Редактировать',
    'add': 'Добавить',
    'close': 'Закрыть',
    'showing': 'Показано',
    'of': 'из',
    'to_top': 'К началу списка',
    
    // Меню и навигация
    'appeals': 'Обращения',
    'social_ideological_work': 'Социальная и идеологическая работа',
    'electronic_appeals': 'Электронные обращения',
    'voluntary_report': 'Добровольное сообщение о небезопасном событии',
    'appeal_methods': 'Способы подачи обращений и порядок рассмотрения',
    'reception_schedules': 'Графики приема',
    'consumer_questionnaire': 'Анкета потребителя аэронавигационных услуг',
    'united_trade_union': 'Объединенная профсоюзная организация',
    'white_rus': 'Белая Русь',
    'brsm': 'БРСМ',
    'belarusian_women_union': 'Белорусский союз женщин',
    'healthy_lifestyle': 'За здоровый образ жизни',
    'improvement_year': 'Год благоустройства',
    'memory_pain': 'Память и боль белорусской земли',
    'version_visually_impaired': 'Версия для слабовидящих',
    'accessibility_settings': 'Настройки доступности',
    'accessibility_mode': 'Режим доступности',
    'enable_visually_impaired': 'Включить версию для слабовидящих',
    'accessibility_mode_description': 'Включает специальные настройки для улучшения доступности сайта',
    'text_settings': 'Настройки текста',
    'font_size': 'Размер шрифта',
    'font_size_recommendation': 'Рекомендуется увеличение до 200% для слабовидящих',
    'line_spacing': 'Межстрочный интервал',
    'line_spacing_recommendation': 'Рекомендуется 1.5x для лучшей читаемости',
    'letter_spacing': 'Межбуквенный интервал',
    'letter_spacing_recommendation': 'Увеличение интервала между буквами для лучшей читаемости',
    'font_family': 'Семейство шрифтов',
    'standard_font': 'Стандартный шрифт',
    'arial_font': 'Arial',
    'arial_recommendation': 'Arial рекомендуется для лучшей читаемости',
    'colors_contrast': 'Цвета и контрастность',
    'contrast': 'Контрастность',
    'normal_contrast': 'Обычная',
    'high_contrast': 'Высокая (7:1)',
    'color_scheme': 'Цветовая схема',
    'dark_scheme': 'Темная',
    'inverted_scheme': 'Инвертированная',
    'color_scheme_description': 'Позволяет выбрать удобную цветовую схему',
    'additional_settings': 'Дополнительные настройки',
    'reduce_motion': 'Уменьшить анимации',
    'reduce_motion_description': 'Отключает анимации для пользователей с вестибулярными расстройствами',
    'show_focus': 'Подсветка фокуса',
    'show_focus_description': 'Четко показывает элемент в фокусе для навигации с клавиатуры',
    'reset': 'Сбросить',
    'apply_settings': 'Применить',
    
    // Заголовки блоков
    'left_upper_block': 'Левый верхний блок',
    'left_middle_block': 'Левый средний блок',
    'left_lower_block': 'Левый нижний блок',
    
    // Название предприятия
    'company_full_name': 'Республиканское унитарное предприятие по аэронавигационному обслуживанию воздушного движения «Белаэронавигация»',
    
    // Личный кабинет
    'profile': 'Личный кабинет',
    'personal_info': 'Личная информация',
    'account_settings': 'Данные аккаунта',
    'security': 'Безопасность',
    'profile_completeness': 'Заполненность профиля',
    'registration_date': 'Регистрация',
    'last_login': 'Последний вход',
    'email_verified': 'Подтвержден',
    'email_not_verified': 'Не подтвержден',
    'account_active': 'Активен',
    'account_blocked': 'Заблокирован',
    'change_password': 'Изменить пароль',
    'current_password': 'Текущий пароль',
    'new_password': 'Новый пароль',
    'confirm_password': 'Подтвердите пароль',
    'delete_account': 'Удалить аккаунт',
    'delete_account_warning': 'Внимание! Это действие необратимо. Все ваши данные будут удалены навсегда.',
    'confirm_password_delete': 'Подтвердите паролем',
    'male': 'Мужской',
    'female': 'Женский',
    'other': 'Другой',
    'choose_gender': 'Выберите пол',
    'about_me': 'О себе',
    'first_name': 'Имя',
    'last_name': 'Фамилия',
    'middle_name': 'Отчество',
    'phone': 'Телефон',
    'date_of_birth': 'Дата рождения',
    'gender': 'Пол',
    'address': 'Адрес',
    'position': 'Должность',
    'department': 'Отдел',
    'enter_first_name': 'Введите имя',
    'enter_last_name': 'Введите фамилию',
    'enter_middle_name': 'Введите отчество',
    'enter_address': 'Введите адрес',
    'enter_position': 'Введите должность',
    'enter_department': 'Введите отдел',
    'tell_about_yourself': 'Расскажите о себе...',
    'profile_updated_successfully': 'Профиль успешно обновлен',
    'error_updating_profile': 'Ошибка при обновлении профиля',
    'passwords_do_not_match': 'Пароли не совпадают',
    'password_min_length': 'Новый пароль должен содержать минимум 6 символов',
    'password_changed_successfully': 'Пароль успешно изменен',
    'error_changing_password': 'Ошибка при изменении пароля',
    'password_info': 'Информация о пароле',
    'last_password_change': 'Последняя смена пароля',
    'password_expired': 'Пароль истек. Требуется смена пароля.',
    'password_expires_soon': 'Пароль нужно будет сменить через {days}',
    'password_expires_in': 'Пароль нужно будет сменить через {days}',
    'password_never_changed': 'Пароль никогда не менялся',
    'password_required': 'Пароль обязателен',
    'force_password_change_title': 'Требуется смена пароля',
    'force_password_change_description': 'Для безопасности вашего аккаунта необходимо изменить пароль при первом входе.',
    'account_deleted_successfully': 'Аккаунт успешно удален',
    'error_deleting_account': 'Ошибка при удалении аккаунта',
    'loading_profile': 'Загрузка профиля...',
    'error_loading_profile': 'Ошибка загрузки профиля',
    'try_again': 'Попробовать снова',
    'try_refresh_page': 'Попробуйте обновить страницу',
    'profile_not_found': 'Профиль не найден',
    'not_authorized_error': 'Возможно, вы не авторизованы или произошла ошибка',
    'manage_profile_settings': 'Управляйте своим профилем и настройками',
    'saving': 'Сохранение...',
    'save_changes': 'Сохранить изменения',
    'password': 'Пароль',
    'change_password_description': 'Измените свой пароль',
    'changing_password': 'Изменение пароля',
    'change_password_description_modal': 'Введите текущий пароль и новый пароль для изменения.',
    'enter_current_password': 'Введите текущий пароль',
    'enter_new_password': 'Введите новый пароль',
    'confirm_new_password': 'Подтвердите новый пароль',
    'changing': 'Изменение...',
    'delete_account_irreversible': 'Это действие необратимо',
    'delete_account_title': 'Удаление аккаунта',
    'delete_account_description': 'Это действие необратимо. Подтвердите паролем для удаления аккаунта.',
    'delete_account_warning_text': 'Внимание! Это действие необратимо. Все ваши данные будут удалены навсегда.',
    'enter_password_confirmation': 'Введите пароль для подтверждения',
    'deleting': 'Удаление...',
    'role': 'Роль',
    
    // Поиск
    'search_results': 'Результаты поиска',
    'search_query': 'По запросу',
    'search_found': 'найдено',
    'search_results_count': 'результатов',
    'search_no_results': 'Ничего не найдено',
    'search_no_results_desc': 'По вашему запросу ничего не найдено. Попробуйте изменить поисковый запрос.',
    'search_min_chars': 'Введите поисковый запрос (минимум 2 символа)',
    'search_loading': 'Поиск...',
    'search_error': 'Ошибка поиска',
    'search_error_desc': 'Произошла ошибка при выполнении поиска. Попробуйте позже.',
    
    // Новости
    'create_news': 'Создать новость',
    'edit_news': 'Редактировать',
    'creating_news': 'Создание новости',
    'editing_news': 'Редактирование новости',
    'title': 'Заголовок',
    'content': 'Содержание',
    'category_id': 'ID категории',
    'file_selected': 'Файл выбран',
    'creating': 'Создание...',
    'create': 'Создать',
    'updating': 'Обновление...',
    'update': 'Обновить',
    'news_created_successfully': 'Новость успешно создана!',
    'error_creating_news': 'Ошибка при создании новости',
    'news_updated_successfully': 'Новость успешно обновлена!',
    'error_updating_news': 'Ошибка при обновлении новости',
    'confirm_delete_news': 'Вы уверены, что хотите удалить новость',
    'news_deleted_successfully': 'Новость успешно удалена!',
    'error_deleting_news': 'Ошибка при удалении новости',
    'error_loading_news': 'Ошибка при загрузке новостей',
    'no_news_yet': 'Новостей пока нет',
    'create_first_news': 'Создайте первую новость, нажав на кнопку выше',
    'current_image': 'Текущее изображение',
  },
  
  en: {
    // General
    'welcome': 'Welcome',
    'home': 'Home',
    'about': 'About',
    'news': 'News',
    'activity': 'Services',
    'air_navigation': 'Air Navigation Information',
    'services': 'Services',
    'contacts': 'Contacts',
    'search': 'Search',
    'login': 'Login',
    'logout': 'Logout',
    'admin_panel': 'Admin Panel',
    'useful_links': 'Useful Links',
    'cookie_policy': 'Cookie Policy',
    'company_name_short': 'RUE "Belaeronavigatsia"',
    'all_rights_reserved': 'All rights reserved',
    
    // About
    'about_company': 'About Company',
    'management': 'Management',
    'structure': 'Company Structure',
    'branches': 'Our Branches',
    'security_policy': 'Security Policy',
    'history': 'History',
    'vacancies': 'Open Vacancies',
    
    // Branches
    'loading_branches': 'Loading branches information...',
    'error_loading_branches': 'Error loading branches data.',
    'please_try_again_later': 'Please try again later.',
    'structural_units': 'Structural Units',
    'branches_not_found': 'Branches not found',
    'data_will_be_added_soon': 'Data will be added soon',
    'invalid_branch_id': 'Invalid branch identifier',
    'loading_branch': 'Loading branch information...',
    'error_loading_branch': 'Failed to load branch data',
    'back_to_list': 'Back to list',
    'contact_phones': 'Contact phones:',
    'description': 'Description',
    'additional_information': 'Additional Information',
    'error_loading_content': 'Error loading content',
    'location_on_map': 'Location on map',
    'address_not_specified': 'Address not specified',
    'address_required_for_map': 'Address must be specified to display the map',
    'additional_photos': 'Additional Photos',
    'image': 'Image',
    'branches_not_available': 'No branches available',
    
    // About Company
    'about_company': 'About the Company',
    'about_company_default_subtitle': 'Information about our enterprise, its structure, goals and principles of work in the field of aeronautical air traffic services.',
    'about_company_placeholder': 'Information about our enterprise, its history, structure and activities will be placed here.',
    'manage_content': 'Manage Content',
    'manage_about_company_content': 'Manage About Company Page Content',
    'edit_about_company_content_description': 'Edit the title, subtitle and main content of the about company page.',
    'page_title': 'Page Title',
    'subtitle': 'Subtitle',
    'company_description_placeholder': 'Brief description of the company...',
    'main_content': 'Main Content',
    'add_content': 'Add Content',
    'content_updated_successfully': 'Page content updated successfully',
    'error_saving_content': 'Error saving content',
    'saving': 'Saving...',
    'edit_page_content_description': 'Edit the title, subtitle and main content of the page in three languages.',
    'subtitle_placeholder': 'Brief description...',
    'management': 'Management',
    'structure': 'Company Structure',
    'branches': 'Our Branches',
    'security_policy': 'Security Policy',
    'history': 'History',
    'vacancies': 'Open Vacancies',
    'go': 'Go',
    'categories_not_found': 'Categories not found',
    'error_loading_data': 'Failed to load data',
    'download': 'Download',
    'unknown_file': 'Unknown file',
    'column': 'Column',
    
    // Voluntary Report
    'voluntary_report_title': 'VOLUNTARY REPORT ON AN UNSAFE EVENT',
    'voluntary_report_description': 'The information included in this report serves exclusively for the purpose of improving flight safety. The full name of the compiler may not be specified. If the name, position, and contact details of the compiler are indicated, they WILL NOT BE SAVED after verification of the received information. Under no circumstances will the identity of the compiler be disclosed or communicated to another official of the enterprise or any other organization.',
    'voluntary_report_warning': 'If the name and position are indicated, they will be excluded from the message after consideration.',
    'compiler_information': 'Information about the compiler',
    'full_name': 'Full Name',
    'enter_full_name': 'Enter Full Name',
    'organization_position_contacts': 'Organization/position, contact details',
    'enter_organization_position_contacts': 'Enter organization/position, contact details',
    'event_information': 'Information about the event',
    'event_date': 'Date of event',
    'event_time': 'Time of event',
    'event_location': 'Place of event',
    'enter_event_location': 'Enter place of event',
    'event_description': 'Description of event',
    'describe_event_in_detail': 'Describe the event in detail',
    'compilation_date': 'Date of information compilation',
    'compilation_time': 'Time of information compilation',
    'recurrence_probability': 'Probability of recurrence of a similar event?',
    'event_consequences': 'What will be the consequences of the event if it recurs?',
    'select_option': 'Select option',
    'very_high': 'Very High',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'very_low': 'Very Low',
    'unknown': 'Unknown',
    'catastrophic': 'Catastrophic',
    'critical': 'Critical',
    'significant': 'Significant',
    'minor': 'Minor',
    'minimal': 'Minimal',
    'sending': 'Sending...',
    'send_message': 'SEND MESSAGE',
    'voluntary_report_sent_successfully': 'Message sent successfully',
    'error_sending_voluntary_report': 'Error sending message',
    
    // Consumer Questionnaire
    'consumer_questionnaire_title': 'Customer Questionnaire for Aeronautical Services of the Republic of Belarus',
    'dear_colleagues': 'Dear Colleagues!',
    'questionnaire_intro_1': 'Thank you for your cooperation with the State Enterprise BELAERONAVIGATSIA. Your opinion on the quality of the aeronautical services provided is of great importance to us and will help us improve the quality of service.',
    'questionnaire_intro_2': 'Please answer the questions below.',
    'user_information': 'USER INFORMATION',
    'user_address': 'User Address',
    'user_name': 'User Name',
    'satisfaction_with_service': 'SATISFACTION WITH PROVIDED AERONAUTICAL SERVICE',
    'satisfaction_5': '5 points - high degree of satisfaction',
    'satisfaction_4': '4 points - good degree of satisfaction',
    'satisfaction_3': '3 points - medium degree of satisfaction',
    'satisfaction_2': '2 points - low degree of satisfaction',
    'satisfaction_1': '1 point - complete dissatisfaction',
    'phraseology_quality': 'Quality of radio exchange phraseology by aviation personnel',
    'information_timeliness': 'Timeliness of informing about air situation',
    'equipment_quality': 'Quality of radio engineering equipment',
    'procedures_quality': 'Quality of air traffic control procedures',
    'select_rating': 'Select rating',
    'satisfaction_reasons': 'Explain the reasons for the decrease in satisfaction rating',
    'describe_satisfaction_reasons': 'Describe the reasons for the decrease in rating...',
    'suggestions_for_improvement': 'Your comments, wishes and suggestions for improving the quality of aeronautical services by our enterprise',
    'your_suggestions': 'Your suggestions for improvement...',
    'completion_date': 'Completion Date',
    'enter_antispam_code': 'Enter antispam code',
    'refresh': 'Refresh',
    'sending_uppercase': 'SENDING...',
    'submit': 'SUBMIT',
    'required_fields_note': '* - fields required for completion',
    'questionnaire_sent_successfully': 'Questionnaire sent successfully!',
    'error_sending_questionnaire': 'Error sending questionnaire',
    'invalid_security_code': 'Invalid security code',
    
    // ELT Forms
    'elt_registration_application': 'ELT REGISTRATION APPLICATION',
    'elt_deregistration_application': 'ELT DEREGISTRATION APPLICATION',
    'elt_registration_basis': 'BASIS FOR ELT REGISTRATION',
    'elt_registration': 'ELT registration',
    'elt_reregistration': 'ELT re-registration',
    'elt_information': 'ELT INFORMATION',
    'elt_15_digit_code': '15-DIGIT HEXADECIMAL TRANSMISSION CODE',
    'model': 'Model',
    'serial_number': 'Serial Number',
    'manufacturer': 'Manufacturer',
    'aircraft_information': 'AIRCRAFT INFORMATION',
    'aircraft_type': 'Aircraft Type',
    'aircraft_model': 'Aircraft Model',
    'aircraft_registration': 'Aircraft Registration Mark',
    'max_people_on_board': 'Maximum number of people on board (crew and passengers)',
    'operator_information': 'AIRCRAFT OPERATOR INFORMATION',
    'aircraft_operator': 'Aircraft Operator',
    'mailing_address': 'Mailing Address',
    'work_phone': 'Work Phone',
    'mobile_phone': 'Mobile Phone',
    'error_sending_form': 'Error sending form',
    'emergency_contact_data': 'EMERGENCY CONTACT DATA',
    'responsible_person_data': 'RESPONSIBLE PERSON DATA FOR REGISTRATION',
    'responsible_person': 'Responsible Person',
    'billing_details': 'BILLING DETAILS',
    'full_organization_name': 'Full Organization Name',
    'short_organization_name': 'Short Organization Name',
    'legal_address': 'Location (Legal Address)',
    'unp': 'UNP',
    'date': 'Date',
    'signature': 'Signature',
    'submit_application': 'SUBMIT APPLICATION',
    'responsible_person_deregistration_data': 'RESPONSIBLE PERSON DATA FOR ELT DEREGISTRATION',
    'document_not_found': 'Document not found',
    'instruction_document_not_found': 'Instruction document not found',
    
    // News
    'all_news': 'All News',
    'back_to_news': 'Back to news',
    'published_by_admin': 'Published by administrator',
    'updated': 'Updated',
    'additional_photos': 'Additional photos',
    'company_news': 'Company News',
    'flight_safety': 'Flight Safety',
    'information_security': 'Information Security',
    'emergency': 'Emergency Services',
    'police': 'Police Information',
    'energy_saving': 'Energy Saving',
    'loading_categories': 'Loading categories...',
    
    // Activity
    'international': 'International Cooperation',
    'standards': 'Air Navigation Standards',
    'hr_policy': 'HR Policy',
    'information_systems': 'Information Systems',
    'training_center': 'Professional Training Center',
    'airport': 'Airport Activities',
    'support': 'Company Support',
    'quality_policy': 'Quality Policy',
    'anti_corruption': 'Anti-Corruption',
    'regulations': 'Regulatory Documents',
    
    // Air Navigation
    'aeronautical_information_subtitle': 'Information about the rules and procedures of aeronautical air traffic services.',
    'appeals': 'Appeals',
    'appeals_subtitle': 'Information about the procedure for filing and consideration of appeals from individuals and legal entities.',
    'services_subtitle': 'Information about the services of the enterprise.',
    'page': 'Page',
    'information': 'Information',
    'eaip': 'Electronic Aeronautical Information Publication (EAIP)',
    'eaip_vfr': 'Electronic Aeronautical Information Publication for Visual Flight Rules (EAIP VFR)',
    'etod': 'Electronic Terrain and Obstacle Data (ETOD)',
    'aip_supplements': 'Aeronautical Information Publication Supplements (AIP SUP)',
    'notam': 'Notices to Airmen (NOTAM)',
    'aircraft_operations': 'Aircraft Operations',
    'air_traffic_services': 'Air Traffic Services',
    'aeronautical_information': 'Aeronautical Information',
    'airspace': 'Airspace',
    'airports': 'Airports',
    'radio_navigation': 'Radio Navigation',
    'weather': 'Meteorology',
    'search_rescue': 'Search and Rescue',
    'aircraft_accidents': 'Aircraft Accidents',
    
    // Services
    'air_navigation_services': 'Air Navigation Services',
    'meteorological_services': 'Meteorological Services',
    'aeronautical_information_services': 'Aeronautical Information Services',
    'search_rescue_services': 'Search and Rescue Services',
    'training_services': 'Training Services',
    'consulting_services': 'Consulting Services',
    'technical_support': 'Technical Support',
    
    // Contacts
    'address': 'Address',
    'phone': 'Phone',
    'email': 'Email',
    'working_hours': 'Working Hours',
    'minsk_address': 'Minsk, Korotkevicha Street, 19',
    'working_time': 'Mon-Fri 8:00-17:00',
    
    // Vacancies
    'vacancy_title': 'Open Vacancies',
    'vacancy_subtitle': 'Join our team of professionals',
    'apply': 'Apply',
    'details': 'Details',
    'requirements': 'Requirements',
    'conditions': 'Working Conditions',
    'salary': 'Salary',
    'location': 'Location',
    'employment_type': 'Employment Type',
    'published': 'Published',
    'send_resume': 'Send Resume',
    'no_vacancies_available': 'No vacancies available',
    'no_vacancies_message': 'There are currently no open vacancies. Please check back later.',
    'loading_vacancies': 'Loading vacancies...',
    'send_by_email': 'Send by Email',
    'description': 'Description',
    'work_conditions': 'Working Conditions',
    'apply_to_vacancy': 'Apply',
    'manage_vacancies_page_content': 'Manage Vacancies Page Content',
    'open_vacancies': 'Open Vacancies',
    'join_our_team_placeholder': 'Join our team...',
    'why_work_with_us': 'Why Work With Us?',
    'stability': 'Stability',
    'stability_description': 'Work in a large state organization with guaranteed employment',
    'development': 'Development',
    'development_description': 'Opportunities for professional growth and training',
    'social_package': 'Social Package',
    'social_package_description': 'Full social package and additional benefits',
    'application_for_vacancy': 'Application for Vacancy',
    'hello': 'Hello!',
    'resume_attached': 'I will attach my resume to the email.',
    'additional_content': 'Additional Content',
    
    // Cookie
    'cookie_title': 'We use cookies',
    'cookie_message': 'We use cookies to improve website performance, analyze traffic and personalize content.',
    'cookie_policy_link': 'Learn more',
    'accept_all': 'Accept All',
    'reject': 'Reject',
    'settings': 'Settings',
    'cookies': 'cookies',
    'necessary_cookies': 'Necessary cookies',
    'necessary_cookies_description': 'These files are necessary for our website to function. Without them, it is impossible to provide the services you request.',
    'functional_cookies': 'Functional cookies',
    'functional_cookies_description': 'These files allow the website to remember your preferences and provide enhanced functionality.',
    'analytics_cookies': 'Analytics cookies',
    'analytics_cookies_description': 'These files help us understand how visitors interact with our website by collecting anonymous information.',
    'marketing_cookies': 'Marketing cookies',
    'marketing_cookies_description': 'These files are used to display relevant advertising and measure the effectiveness of advertising campaigns.',
    'save_preferences': 'Save Preferences',
    'cookie_policy': 'Cookie Usage Policy',
    'last_updated': 'Last updated',
    'your_current_cookie_settings': 'Your current cookie settings',
    'always_enabled': 'Always enabled',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'change_cookie_settings': 'Change cookie settings',
    'what_are_cookies': 'What are cookies?',
    'cookies_description': 'Cookies are small text files that websites store on your device (computer, tablet, or mobile phone) when you visit. They help websites remember information about your visit, making subsequent visits more convenient and useful.',
    'what_types_of_cookies_do_we_use': 'What types of cookies do we use?',
    'examples_of_use': 'Examples of use:',
    'save_auth_state': 'Saving authorization state',
    'remember_cart_items': 'Remembering items in the cart',
    'security_protection': 'Ensuring security and protection against fraud',
    'save_language_preferences': 'Saving language preferences',
    'remember_region_language': 'Remembering selected region or language',
    'save_display_settings': 'Saving display settings',
    'content_personalization': 'Content personalization',
    'improve_user_experience': 'Improving user experience',
    'count_visitors': 'Counting visitors',
    'analyze_popular_pages': 'Analyzing most popular pages',
    'determine_traffic_sources': 'Determining traffic sources',
    'improve_site_performance': 'Improving website performance',
    'we_may_use_services': 'We may use services',
    'show_personalized_ads': 'Showing personalized advertising',
    'track_conversions': 'Tracking conversions',
    'retargeting': 'Retargeting',
    'ad_campaign_analytics': 'Advertising campaign analytics',
    'how_to_manage_cookies': 'How to manage cookies?',
    'manage_cookies_description': 'You can control and/or delete cookies at your discretion. You can delete all cookies that are already on your computer and configure most browsers so that they are not saved.',
    'browser_management': 'Browser management:',
    'chrome_cookie_path': 'Settings → Privacy and Security → Cookies',
    'firefox_cookie_path': 'Settings → Privacy & Security → Cookies',
    'safari_cookie_path': 'Settings → Privacy → Cookies',
    'edge_cookie_path': 'Settings → Cookies and site permissions',
    'disable_cookies_warning': 'Please note that if you disable cookies, some features of our website may not work correctly.',
    'cookie_storage_period': 'Cookie storage period',
    'we_use_both_cookie_types': 'We use both session and persistent cookies:',
    'session_cookies': 'Session cookies',
    'session_cookies_description': 'temporary files that are deleted when the browser is closed',
    'persistent_cookies': 'Persistent cookies',
    'persistent_cookies_description': 'remain on your device until expiration or manual deletion (usually up to 12 months)',
    'cookie_policy_questions': 'If you have questions about our cookie usage policy, please contact us:',
    'organization': 'Organization',
    'company_full_name': 'Republican Unitary Enterprise for Air Navigation Services "Belaeronavigatsia"',
    'company_address': 'Minsk, Korotkevich St., 19',
    'phone': 'Phone',
    'fax': 'fax',
    'go_back': 'Go back',
    
    // Admin Panel
    'user_management': 'User Management',
    'role_management': 'Role Management',
    'news_management': 'News Management',
    'category_management': 'Category Management',
    'branch_management': 'Branch Management',
    'vacancy_management': 'Vacancy Management',
    'management_management': 'Management Management',
    'management_title': 'MANAGEMENT OF THE STATE ENTERPRISE «BELAERONAVIGATION»',
    'loading_managers': 'Loading management information...',
    'no_managers_info': 'Management information is not available',
    'data_will_be_added': 'Data will be added soon',
    'book_appointment': 'Book an appointment',
    'hide_booking': 'Hide booking',
    'booking_appointment': 'Book an appointment',
    'fill_booking_form': 'Fill out the form to book an appointment with the manager',
    'selected_time': 'Selected time',
    'full_name': 'Full name',
    'enter_full_name': 'Enter your full name',
    'enter_email': 'Enter your email',
    'additional_info': 'Additional information',
    'describe_visit_purpose': 'Describe the purpose of the visit (optional)',
    'book': 'Book',
    'booking_success': 'Appointment successfully booked!',
    'booking_error': 'Error booking appointment',
    'fill_required_fields': 'Fill in all required fields',
    'booking_slots': 'Booking slots',
    'loading_schedule': 'Loading schedule...',
    'booked': 'Booked',
    'unavailable': 'Unavailable',
    'no_available_slots': 'No available booking slots',
    'contact_administrator': 'Contact administrator to set up schedule',
    'reception_schedule': 'Reception schedule',
    'offices': 'Offices',
    
    // Additional
    'loading': 'Loading...',
    'error': 'Error',
    'no_data': 'No data',
    'read_more': 'Read more',
    'back': 'Back',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'close': 'Close',
    'showing': 'Showing',
    'of': 'of',
    'to_top': 'To the top',
    
    // Menu and navigation
    'appeals': 'Appeals',
    'social_ideological_work': 'Social and Ideological Work',
    'electronic_appeals': 'Electronic Appeals',
    'voluntary_report': 'Voluntary Report on Unsafe Event',
    'appeal_methods': 'Methods of Submitting Appeals and Procedure for Consideration',
    'reception_schedules': 'Reception Schedules',
    'consumer_questionnaire': 'Questionnaire for Consumer of Air Navigation Services',
    'united_trade_union': 'United Trade Union Organization',
    'white_rus': 'White Rus',
    'brsm': 'BRSM',
    'belarusian_women_union': 'Belarusian Women Union',
    'healthy_lifestyle': 'For Healthy Lifestyle',
    'improvement_year': 'Year of Improvement',
    'memory_pain': 'Memory and Pain of the Belarusian Land',
    'version_visually_impaired': 'Version for Visually Impaired',
    'accessibility_settings': 'Accessibility Settings',
    'accessibility_mode': 'Accessibility Mode',
    'enable_visually_impaired': 'Enable version for visually impaired',
    'accessibility_mode_description': 'Enables special settings to improve site accessibility',
    'text_settings': 'Text Settings',
    'font_size': 'Font Size',
    'font_size_recommendation': 'Recommended increase up to 200% for visually impaired',
    'line_spacing': 'Line Spacing',
    'line_spacing_recommendation': 'Recommended 1.5x for better readability',
    'letter_spacing': 'Letter Spacing',
    'letter_spacing_recommendation': 'Increase interval between letters for better readability',
    'font_family': 'Font Family',
    'standard_font': 'Standard Font',
    'arial_font': 'Arial',
    'arial_recommendation': 'Arial is recommended for better readability',
    'colors_contrast': 'Colors and Contrast',
    'contrast': 'Contrast',
    'normal_contrast': 'Normal',
    'high_contrast': 'High (7:1)',
    'color_scheme': 'Color Scheme',
    'dark_scheme': 'Dark',
    'inverted_scheme': 'Inverted',
    'color_scheme_description': 'Allows you to choose a convenient color scheme',
    'additional_settings': 'Additional Settings',
    'reduce_motion': 'Reduce Animations',
    'reduce_motion_description': 'Disables animations for users with vestibular disorders',
    'show_focus': 'Focus Highlight',
    'show_focus_description': 'Clearly shows the focused element for keyboard navigation',
    'reset': 'Reset',
    'apply_settings': 'Apply',
    
    // Block headers
    'left_upper_block': 'Left Upper Block',
    'left_middle_block': 'Left Middle Block',
    'left_lower_block': 'Left Lower Block',
    
    // Company name
    'company_full_name': 'Republican Unitary Enterprise for Aeronautical Air Traffic Services «Belaeronavigatsia»',
    
    // User Profile
    'profile': 'User Profile',
    'personal_info': 'Personal Information',
    'account_settings': 'Account Settings',
    'security': 'Security',
    'profile_completeness': 'Profile Completeness',
    'registration_date': 'Registration',
    'last_login': 'Last Login',
    'email_verified': 'Verified',
    'email_not_verified': 'Not Verified',
    'account_active': 'Active',
    'account_blocked': 'Blocked',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password': 'Confirm Password',
    'delete_account': 'Delete Account',
    'delete_account_warning': 'Warning! This action is irreversible. All your data will be permanently deleted.',
    'confirm_password_delete': 'Confirm Password',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'choose_gender': 'Choose Gender',
    'about_me': 'About Me',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'middle_name': 'Middle Name',
    'phone': 'Phone',
    'date_of_birth': 'Date of Birth',
    'gender': 'Gender',
    'address': 'Address',
    'position': 'Position',
    'department': 'Department',
    'enter_first_name': 'Enter first name',
    'enter_last_name': 'Enter last name',
    'enter_middle_name': 'Enter middle name',
    'enter_address': 'Enter address',
    'enter_position': 'Enter position',
    'enter_department': 'Enter department',
    'tell_about_yourself': 'Tell us about yourself...',
    'profile_updated_successfully': 'Profile updated successfully',
    'error_updating_profile': 'Error updating profile',
    'passwords_do_not_match': 'Passwords do not match',
    'password_min_length': 'New password must contain at least 6 characters',
    'password_changed_successfully': 'Password changed successfully',
    'error_changing_password': 'Error changing password',
    'password_info': 'Password Information',
    'last_password_change': 'Last Password Change',
    'password_expired': 'Password expired. Password change required.',
    'password_expires_soon': 'Password needs to be changed in {days}',
    'password_expires_in': 'Password needs to be changed in {days}',
    'password_never_changed': 'Password has never been changed',
    'password_required': 'Password is required',
    'force_password_change_title': 'Password Change Required',
    'force_password_change_description': 'For your account security, you must change your password on first login.',
    'account_deleted_successfully': 'Account deleted successfully',
    'error_deleting_account': 'Error deleting account',
    'loading_profile': 'Loading profile...',
    'error_loading_profile': 'Error loading profile',
    'try_again': 'Try again',
    'try_refresh_page': 'Try refreshing the page',
    'profile_not_found': 'Profile not found',
    'not_authorized_error': 'You may not be authorized or an error occurred',
    'manage_profile_settings': 'Manage your profile and settings',
    'saving': 'Saving...',
    'save_changes': 'Save changes',
    'password': 'Password',
    'change_password_description': 'Change your password',
    'changing_password': 'Changing Password',
    'change_password_description_modal': 'Enter your current password and new password to change.',
    'enter_current_password': 'Enter current password',
    'enter_new_password': 'Enter new password',
    'confirm_new_password': 'Confirm new password',
    'changing': 'Changing...',
    'delete_account_irreversible': 'This action is irreversible',
    'delete_account_title': 'Delete Account',
    'delete_account_description': 'This action is irreversible. Confirm with password to delete account.',
    'delete_account_warning_text': 'Warning! This action is irreversible. All your data will be permanently deleted.',
    'enter_password_confirmation': 'Enter password for confirmation',
    'deleting': 'Deleting...',
    'role': 'Role',
    
    // Search
    'search_results': 'Search Results',
    'search_query': 'For query',
    'search_found': 'found',
    'search_results_count': 'results',
    'search_no_results': 'No Results Found',
    'search_no_results_desc': 'No results found for your query. Try modifying your search.',
    'search_min_chars': 'Enter search query (minimum 2 characters)',
    'search_loading': 'Searching...',
    'search_error': 'Search Error',
    'search_error_desc': 'An error occurred while searching. Please try again later.',
    
    // News
    'create_news': 'Create News',
    'edit_news': 'Edit',
    'creating_news': 'Creating News',
    'editing_news': 'Editing News',
    'title': 'Title',
    'content': 'Content',
    'category_id': 'Category ID',
    'file_selected': 'File selected',
    'creating': 'Creating...',
    'create': 'Create',
    'updating': 'Updating...',
    'update': 'Update',
    'news_created_successfully': 'News created successfully!',
    'error_creating_news': 'Error creating news',
    'news_updated_successfully': 'News updated successfully!',
    'error_updating_news': 'Error updating news',
    'confirm_delete_news': 'Are you sure you want to delete the news',
    'news_deleted_successfully': 'News deleted successfully!',
    'error_deleting_news': 'Error deleting news',
    'error_loading_news': 'Error loading news',
    'no_news_yet': 'No news yet',
    'create_first_news': 'Create the first news by clicking the button above',
    'current_image': 'Current image',
  },
  
  be: {
    // Агульныя
    'welcome': 'Сардэчна запрашаем',
    'home': 'Галоўная',
    'about': 'Пра прадпрыемства',
    'news': 'Навіны',
    'activity': 'Дзейнасць',
    'air_navigation': 'Аэранавігацыйная інфармацыя',
    'services': 'Паслугі',
    'contacts': 'Кантакты',
    'search': 'Пошук',
    'login': 'Увайсці',
    'logout': 'Выйсці',
    'admin_panel': 'Панэль адміністратара',
    'useful_links': 'Карысныя спасылкі',
    'cookie_policy': 'Палітыка выкарыстання cookie',
    'company_name_short': 'РУП «Белаэранавігацыя»',
    'all_rights_reserved': 'Усе правы абаронены',
    
    // Пра прадпрыемства
    'about_company': 'Пра прадпрыемства',
    'management': 'Кіраўніцтва',
    'structure': 'Структура прадпрыемства',
    'branches': 'Нашы філіялы',
    'security_policy': 'Палітыка бяспекі',
    'history': 'Гісторыя',
    'vacancies': 'Адкрытыя вакансіі',
    
    // Філіялы
    'loading_branches': 'Загрузка інфармацыі пра філіялы...',
    'error_loading_branches': 'Памылка загрузкі даных пра філіялы.',
    'please_try_again_later': 'Калі ласка, паспрабуйце яшчэ раз пазней.',
    'structural_units': 'Структурныя падраздзяленні',
    'branches_not_found': 'Філіялы не знойдзены',
    'data_will_be_added_soon': 'Даныя будуць дададзены ў бліжэйшы час',
    'invalid_branch_id': 'Няправільны ідэнтыфікатар філіяла',
    'loading_branch': 'Загрузка інфармацыі пра філіял...',
    'error_loading_branch': 'Не ўдалося загрузіць даныя пра філіял',
    'back_to_list': 'Назад да спісу',
    'contact_phones': 'Кантактныя тэлефоны:',
    'description': 'Апісанне',
    'additional_information': 'Дадатковая інфармацыя',
    'error_loading_content': 'Памылка загрузкі кантэнту',
    'location_on_map': 'Размяшчэнне на карце',
    'address_not_specified': 'Адрас не паказаны',
    'address_required_for_map': 'Для адлюстравання карты неабходна паказаць адрас',
    'additional_photos': 'Дадатковыя фота',
    'image': 'Выява',
    'branches_not_available': 'Філіялы не даступныя',
    
    // Пра прадпрыемства
    'about_company': 'Пра прадпрыемства',
    'about_company_default_subtitle': 'Інфармацыя пра наша прадпрыемства, яго структуру, мэты і прынцыпы работы ў галіне аэранавігацыйнага абслугоўвання паветранага руху.',
    'about_company_placeholder': 'Тут будзе размешчана інфармацыя пра наша прадпрыемства, яго гісторыю, структуру і дзейнасць.',
    'manage_content': 'Кіраванне кантэнтам',
    'manage_about_company_content': 'Кіраванне кантэнтам старонкі пра прадпрыемства',
    'edit_about_company_content_description': 'Рэдагуйце загаловак, падзагаловак і асноўны кантэнт старонкі пра прадпрыемства.',
    'page_title': 'Загаловак старонкі',
    'subtitle': 'Падзагаловак',
    'company_description_placeholder': 'Кароткае апісанне прадпрыемства...',
    'main_content': 'Асноўны кантэнт',
    'add_content': 'Дадаць кантэнт',
    'content_updated_successfully': 'Кантэнт старонкі паспяхова абноўлены',
    'error_saving_content': 'Памылка пры захаванні кантэнту',
    'saving': 'Захаванне...',
    'edit_page_content_description': 'Рэдагуйце загаловак, падзагаловак і асноўны кантэнт старонкі на трох мовах.',
    'subtitle_placeholder': 'Кароткае апісанне...',
    'management': 'Кіраўніцтва',
    'structure': 'Структура прадпрыемства',
    'branches': 'Нашы філіялы',
    'security_policy': 'Палітыка бяспекі',
    'history': 'Гісторыя',
    'vacancies': 'Адкрытыя вакансіі',
    'go': 'Перайсці',
    'categories_not_found': 'Катэгорыі не знойдзены',
    'error_loading_data': 'Не ўдалося загрузіць даныя',
    'download': 'Спампаваць',
    'unknown_file': 'Невядомы файл',
    'column': 'Калонка',
    
    // Дабраахвотнае паведамленне
    'voluntary_report_title': 'ДАБРААХВОТНАЕ ПАВЕДАМЛЕННЕ ПРА НЕБЯСПЕЧНАЕ ЗДАРЭННЕ',
    'voluntary_report_description': 'Інфармацыя, якая ўключаецца ў дадзенае паведамленне, служыць выключна мэтам павышэння бяспекі палётаў. Прозвішча, імя, імя па бацьку складальніка паведамлення можна не паказваць. Калі імя, пасада, кантактныя даныя складальніка паказваюцца, то яны НЕ БУДУЦЬ ЗАХОЙВАНЫ, пасля праверкі паступіўшай інфармацыі. Ні пры якіх абставінах асоба складальніка не будзе раскрыта або паведамлена іншай службовай асобе прадпрыемства або іншай арганізацыі.',
    'voluntary_report_warning': 'Калі імя і пасада паказваюцца, то пасля разгляду яны будуць выключаны з паведамлення.',
    'compiler_information': 'Інфармацыя пра складальніка',
    'full_name': 'Прозвішча, імя, імя па бацьку',
    'enter_full_name': 'Увядзіце прозвішча, імя, імя па бацьку',
    'organization_position_contacts': 'Арганізацыя/пасада, кантактныя даныя',
    'enter_organization_position_contacts': 'Увядзіце арганізацыю/пасаду, кантактныя даныя',
    'event_information': 'Інфармацыя пра здарэнне',
    'event_date': 'Дата здарэння',
    'event_time': 'Час здарэння',
    'event_location': 'Месца здарэння',
    'enter_event_location': 'Увядзіце месца здарэння',
    'event_description': 'Апісанне здарэння',
    'describe_event_in_detail': 'Падрабязна апішыце здарэнне',
    'compilation_date': 'Дата складання інфармацыі пра здарэнне',
    'compilation_time': 'Час складання інфармацыі пра здарэнне',
    'recurrence_probability': 'Верагоднасць паўтору падобнага здарэння?',
    'event_consequences': 'Якія будуць наступствы здарэння, калі яно паўторыцца?',
    'select_option': 'Выберыце варыянт',
    'very_high': 'Вельмі высокая',
    'high': 'Высокая',
    'medium': 'Сярэдняя',
    'low': 'Нізкая',
    'very_low': 'Вельмі нізкая',
    'unknown': 'Невядома',
    'catastrophic': 'Катастрафічныя',
    'critical': 'Крытычныя',
    'significant': 'Значныя',
    'minor': 'Нязначныя',
    'minimal': 'Мінімальныя',
    'sending': 'Адпраўка...',
    'send_message': 'АДПРАВІЦЬ ПАВЕДАМЛЕННЕ',
    'voluntary_report_sent_successfully': 'Паведамленне паспяхова адпраўлена',
    'error_sending_voluntary_report': 'Памылка пры адпраўцы паведамлення',
    
    // Анкета спажыўца
    'consumer_questionnaire_title': 'Анкета спажыўца аэранавігацыйных паслуг Рэспублікі Беларусь',
    'dear_colleagues': 'Шаноўныя Калегі!',
    'questionnaire_intro_1': 'Дзякуем Вас за супрацоўніцтва з Дзяржаўным прадпрыемствам БЕЛАЭРОНАВИГАЦИЯ. Ваша меркаванне пра якасць прадастаўляемых аэранавігацыйных паслуг мае для нас вялікае значэнне і дапаможа нам палепшыць якасць абслугоўвання.',
    'questionnaire_intro_2': 'Просім Вас адказаць на пытанні, прадстаўленыя ніжэй.',
    'user_information': 'ІНФАРМАЦЫЯ ПРА КАРЫСТАЛЬНІКА',
    'user_address': 'Адрас карыстальніка',
    'user_name': 'Найменне карыстальніка',
    'satisfaction_with_service': 'ЗДАВОЛЬНЕНАСЦЬ АКАЗАНАЙ АЭРОНАВІГАЦЫЙНАЙ ПАСЛУГАЙ',
    'satisfaction_5': '5 балаў - высокая ступень задаволенасці',
    'satisfaction_4': '4 балы - добрая ступень задаволенасці',
    'satisfaction_3': '3 балы - сярэдняя ступень задаволенасці',
    'satisfaction_2': '2 балы - нізкая ступень задаволенасці',
    'satisfaction_1': '1 бал - поўная незадаволенасць',
    'phraseology_quality': 'Якасць вядзення фразеалогіі радыёабмену авіяцыйным персаналам',
    'information_timeliness': 'Своечасовасць інфармавання пра паветраную абстаноўку',
    'equipment_quality': 'Якасць работы радыётэхнічных сродкаў',
    'procedures_quality': 'Якасць працэдур абслугоўвання паветранага руху',
    'select_rating': 'Выберыце ацэнку',
    'satisfaction_reasons': 'Растлумачце прычыны зніжэння ацэнкі задаволенасці',
    'describe_satisfaction_reasons': 'Апішыце прычыны зніжэння ацэнкі...',
    'suggestions_for_improvement': 'Вашы заўвагі, пажаданні і прапановы па паляпшэнню якасці аэранавігацыйных паслуг нашым прадпрыемствам',
    'your_suggestions': 'Вашы прапановы па паляпшэнню...',
    'completion_date': 'Дата запоўнення',
    'enter_antispam_code': 'Увядзіце антыспам код',
    'refresh': 'Абнавіць',
    'sending_uppercase': 'АДПРАЎКА...',
    'submit': 'АДПРАВІЦЬ',
    'required_fields_note': '* - палі, абавязковыя для запоўнення',
    'questionnaire_sent_successfully': 'Анкета паспяхова адпраўлена!',
    'error_sending_questionnaire': 'Памылка пры адпраўцы анкеты',
    'invalid_security_code': 'Няверны код бяспекі',
    
    // ELT формы
    'elt_registration_application': 'ЗАЯЎЛЕННЕ ПРА РЭГІСТРАЦЫЮ ELT',
    'elt_deregistration_application': 'ЗАЯЎЛЕННЕ ПРА ЗНЯЦЦЕ З РЭГІСТРАЦЫІ ELT',
    'elt_registration_basis': 'АСНОВА ДЛЯ РЭГІСТРАЦЫІ ELT',
    'elt_registration': 'рэгістрацыя ELT',
    'elt_reregistration': 'перарэгістрацыя ELT',
    'elt_information': 'ІНФАРМАЦЫЯ ПРА ELT',
    'elt_15_digit_code': '15-ЗНАЧНЫ ШАСНАЦЦАТКОВЫ КОД ПАСЫЛКІ',
    'model': 'Мадэль',
    'serial_number': 'Заводскі нумар',
    'manufacturer': 'Вытворца',
    'aircraft_information': 'ІНФАРМАЦЫЯ ПРА ПАВЕТРАНАЕ СУДНА',
    'aircraft_type': 'Тып паветранага судна',
    'aircraft_model': 'Мадэль паветранага судна',
    'aircraft_registration': 'Рэгістрацыйны знак паветранага судна',
    'max_people_on_board': 'Максімальная колькасць людзей на борце (экіпаж і пасажыры)',
    'operator_information': 'ІНФАРМАЦЫЯ ПРА ЭКСПЛУАТАНТА ПАВЕТРАНАГА СУДНА',
    'aircraft_operator': 'Эксплуатант паветранага судна',
    'mailing_address': 'Паштовы адрас',
    'work_phone': 'Рабочы тэлефон',
    'mobile_phone': 'Мабільны тэлефон',
    'error_sending_form': 'Памылка пры адпраўцы формы',
    'emergency_contact_data': 'ДАНЫЯ ДЛЯ СУВЯЗІ У ВЫПАДКУ БЕДСТВА',
    'responsible_person_data': 'ДАНЫЯ АДКАЗНАГА ЗА РЭГІСТРАЦЫЮ',
    'responsible_person': 'Адказная асоба',
    'billing_details': 'РЭКВІЗІТЫ ДЛЯ ВЫСТАЎЛЕННЯ РАХУНКУ',
    'full_organization_name': 'Поўная назва арганізацыі',
    'short_organization_name': 'Скарочаная назва арганізацыі',
    'legal_address': 'Месца знаходжання (юрыдычны адрас)',
    'unp': 'УНП',
    'date': 'Дата',
    'signature': 'Подпіс',
    'submit_application': 'АДПРАВІЦЬ ЗАЯЎЛЕННЕ',
    'responsible_person_deregistration_data': 'ДАНЫЯ АДКАЗНАГА ЗА ЗНЯЦЦЕ З РЭГІСТРАЦЫІ ELT',
    'document_not_found': 'Дакумент не знойдзены',
    'instruction_document_not_found': 'Дакумент інструкцыі не знойдзены',
    
    // Навіны
    'all_news': 'Усе навіны',
    'back_to_news': 'Назад да навін',
    'published_by_admin': 'Апублікавана адміністратарам',
    'updated': 'Абноўлена',
    'additional_photos': 'Дадатковыя фота',
    'company_news': 'Навіны прадпрыемства',
    'flight_safety': 'Бяспека палётаў',
    'information_security': 'Інфармацыйная бяспека',
    'emergency': 'МНС інфармуе',
    'police': 'МУС інфармуе',
    'energy_saving': 'Энергазберажэнне',
    'loading_categories': 'Загрузка катэгорый...',
    
    // Дзейнасць
    'international': 'Міжнароднае супрацоўніцтва',
    'standards': 'Стандарты ў галіне аэранавігацыі',
    'hr_policy': 'Кадравая палітыка',
    'information_systems': 'Інфармацыйныя сістэмы',
    'training_center': 'Цэнтр прафесійнай падрыхтоўкі',
    'airport': 'Аэрапортавая дзейнасць',
    'support': 'Забеспячэнне дзейнасці прадпрыемства',
    'quality_policy': 'Палітыка ў галіне якасці',
    'anti_corruption': 'Супрацьдзеянне карупцыі',
    'regulations': 'Нарматыўныя дакументы',
    
    // Аэранавігацыя
    'aeronautical_information_subtitle': 'Інфармацыя пра правілы і працэдуры аэранавігацыйнага абслугоўвання паветранага руху.',
    'appeals': 'Звароты',
    'appeals_subtitle': 'Інфармацыя пра парадак падачы і разгляду зваротаў грамадзян і юрыдычных асоб.',
    'services_subtitle': 'Інфармацыя пра паслугі прадпрыемства.',
    'page': 'Старонка',
    'information': 'Інфармацыя',
    'eaip': 'Зборнік аэранавігацыйнай інфармацыі (EAIP)',
    'eaip_vfr': 'Зборнік аэранавігацыйнай інфармацыі для візуальных палётаў (EAIP VFR)',
    'etod': 'Электронныя даныя аб мясцовасці і перашкодах (ETOD)',
    'aip_supplements': 'Дапаўненні да зборніка аэранавігацыйнай інфармацыі (AIP SUP)',
    'notam': 'Паведамленні авіяцыйным службам (NOTAM)',
    'aircraft_operations': 'Эксплуатацыя паветраных суднаў',
    'air_traffic_services': 'Службы паветранага руху',
    'aeronautical_information': 'Аэранавігацыйная інфармацыя',
    'airspace': 'Паветранная прастора',
    'airports': 'Аэрадромы',
    'radio_navigation': 'Радыёнавігацыя',
    'weather': 'Метэаралогія',
    'search_rescue': 'Пошук і ратаванне',
    'aircraft_accidents': 'Авіяцыйныя здарэнні',
    
    // Паслугі
    'air_navigation_services': 'Аэранавігацыйнае абслугоўванне',
    'meteorological_services': 'Метэаралагічнае абслугоўванне',
    'aeronautical_information_services': 'Аэранавігацыйнае інфармацыйнае абслугоўванне',
    'search_rescue_services': 'Службы пошуку і ратавання',
    'training_services': 'Паслугі па падрыхтоўцы персаналу',
    'consulting_services': 'Кансультацыйныя паслугі',
    'technical_support': 'Тэхнічная падтрымка',
    
    // Кантакты
    'address': 'Адрас',
    'phone': 'Тэлефон',
    'email': 'Email',
    'working_hours': 'Час работы',
    'minsk_address': 'г. Мінск, вул. Караткевiча, 19',
    'working_time': 'Пн-Пт 8:00-17:00',
    
    // Вакансіі
    'vacancy_title': 'Адкрытыя вакансіі',
    'vacancy_subtitle': 'Далучайцеся да нашай каманды прафесіяналаў',
    'apply': 'Адгукнуцца',
    'details': 'Падрабязна',
    'requirements': 'Патрабаванні',
    'conditions': 'Умовы работы',
    'salary': 'Зарплата',
    'location': 'Месцазнаходжанне',
    'employment_type': 'Тып занятасці',
    'published': 'Апублікавана',
    'send_resume': 'Адправіць рэзюмэ',
    'no_vacancies_available': 'Няма даступных вакансій',
    'no_vacancies_message': 'У цяперашні час адкрытых вакансій няма. Калі ласка, зайдзіце пазней.',
    'loading_vacancies': 'Загрузка вакансій...',
    'send_by_email': 'Адправіць на пошту',
    'description': 'Апісанне',
    'work_conditions': 'Умовы работы',
    'apply_to_vacancy': 'Адгукнуцца',
    'manage_vacancies_page_content': 'Кіраванне кантэнтам старонкі вакансій',
    'open_vacancies': 'Адкрытыя вакансіі',
    'join_our_team_placeholder': 'Далучайцеся да нашай каманды...',
    'why_work_with_us': 'Чаму варта працаваць з намі?',
    'stability': 'Стабільнасць',
    'stability_description': 'Праца ў буйной дзяржаўнай арганізацыі з гарантаванай занятасцю',
    'development': 'Развіццё',
    'development_description': 'Магчымасці для прафесійнага росту і навучання',
    'social_package': 'Сацыяльны пакет',
    'social_package_description': 'Поўны сацыяльны пакет і дадатковыя льготы',
    'application_for_vacancy': 'Адгук на вакансію',
    'hello': 'Прывітанне!',
    'resume_attached': 'Рэзюмэ прымацавана да ліста.',
    'additional_content': 'Дадатковы кантэнт',
    
    // Cookie
    'cookie_title': 'Мы выкарыстоўваем cookie-файлы',
    'cookie_message': 'Мы выкарыстоўваем cookie-файлы для паляпшэння работы сайта, аналізу трафіку і персаналізацыі кантэнту.',
    'cookie_policy_link': 'Падрабязней',
    'accept_all': 'Прыняць усе',
    'reject': 'Адхіліць',
    'settings': 'Налады',
    'cookies': 'cookie',
    'necessary_cookies': 'Неабходныя cookie',
    'necessary_cookies_description': 'Гэтыя файлы неабходныя для работы нашага вэб-сайта. Без іх немагчыма прадаставіць запытаныя вамі паслугі.',
    'functional_cookies': 'Функцыянальныя cookie',
    'functional_cookies_description': 'Гэтыя файлы дазваляюць вэб-сайту запомніць вашы перавагі і забяспечваюць пашыраную функцыянальнасць.',
    'analytics_cookies': 'Аналітычныя cookie',
    'analytics_cookies_description': 'Гэтыя файлы дапамагаюць нам зразумець, як наведвальнікі ўзаемадзейнічаюць з нашым вэб-сайтам, збіраючы ананімную інфармацыю.',
    'marketing_cookies': 'Маркетынгавыя cookie',
    'marketing_cookies_description': 'Гэтыя файлы выкарыстоўваюцца для паказу рэлевантнай рэкламы і вымярэння эфектыўнасці рэкламных кампаній.',
    'save_preferences': 'Захаваць налады',
    'cookie_policy': 'Палітыка выкарыстання cookie',
    'last_updated': 'Апошняе абнаўленне',
    'your_current_cookie_settings': 'Вашы бягучыя налады cookie',
    'always_enabled': 'Заўсёды ўключаны',
    'enabled': 'Уключаны',
    'disabled': 'Выключаны',
    'change_cookie_settings': 'Змяніць налады cookie',
    'what_are_cookies': 'Што такое cookie?',
    'cookies_description': 'Cookie (кукі) — гэта невялікія тэкставыя файлы, якія вэб-сайты захоўваюць на вашай прыладзе (камп\'ютары, планшэце або мабільным тэлефоне) пры наведванні. Яны дапамагаюць вэб-сайтам запомніць інфармацыю пра ваш візіт, што робіць наступныя наведванні больш зручнымі і карыснымі.',
    'what_types_of_cookies_do_we_use': 'Якія тыпы cookie мы выкарыстоўваем?',
    'examples_of_use': 'Прыклады выкарыстання:',
    'save_auth_state': 'Захаванне стану аўтарызацыі',
    'remember_cart_items': 'Запамінанне тавараў у кошыку',
    'security_protection': 'Забеспячэнне бяспекі і абарона ад махлярства',
    'save_language_preferences': 'Захаванне моўных пераваг',
    'remember_region_language': 'Запамінанне выбранага рэгіёна або мовы',
    'save_display_settings': 'Захаванне настроек адлюстравання',
    'content_personalization': 'Персаналізацыя кантэнту',
    'improve_user_experience': 'Паляпшэнне карыстацкага вопыту',
    'count_visitors': 'Падлік колькасці наведвальнікаў',
    'analyze_popular_pages': 'Аналіз найбольш папулярных старонак',
    'determine_traffic_sources': 'Вызначэнне крыніц трафіку',
    'improve_site_performance': 'Паляпшэнне прадукцыйнасці сайта',
    'we_may_use_services': 'Мы можам выкарыстоўваць сэрвісы',
    'show_personalized_ads': 'Паказ персаналізаванай рэкламы',
    'track_conversions': 'Адсочванне канверсій',
    'retargeting': 'Рэтаргетынг',
    'ad_campaign_analytics': 'Аналітыка рэкламных кампаній',
    'how_to_manage_cookies': 'Як кіраваць cookie?',
    'manage_cookies_description': 'Вы можаце кантраляваць і/або выдаляць cookie на сваё меркаванне. Вы можаце выдаліць усе cookie, якія ўжо знаходзяцца на вашым камп\'ютары, і наладзіць большасць браўзераў так, каб яны не захоўваліся.',
    'browser_management': 'Кіраванне праз браўзер:',
    'chrome_cookie_path': 'Налады → Канфідэнцыяльнасць і бяспека → Файлы cookie',
    'firefox_cookie_path': 'Налады → Прыватнасць і абарона → Файлы cookie',
    'safari_cookie_path': 'Налады → Канфідэнцыяльнасць → Файлы cookie',
    'edge_cookie_path': 'Налады → Файлы cookie і дазволы сайтаў',
    'disable_cookies_warning': 'Звярніце ўвагу, што калі вы адключыце cookie, некаторыя функцыі нашага вэб-сайта могуць працаваць няправільна.',
    'cookie_storage_period': 'Тэрмін захоўвання cookie',
    'we_use_both_cookie_types': 'Мы выкарыстоўваем як сесійныя, так і пастаянныя cookie:',
    'session_cookies': 'Сесійныя cookie',
    'session_cookies_description': 'часовыя файлы, якія выдаляюцца пры закрыцці браўзера',
    'persistent_cookies': 'Пастаянныя cookie',
    'persistent_cookies_description': 'застаюцца на вашай прыладзе да сканчэння тэрміну дзеяння або выдалення ўручную (звычайна да 12 месяцаў)',
    'cookie_policy_questions': 'Калі ў вас ёсць пытанні пра нашу палітыку выкарыстання cookie, звяжыцеся з намі:',
    'organization': 'Арганізацыя',
    'company_full_name': 'Рэспубліканскае ўнітарнае прадпрыемства па аэранавігацыйным абслугоўванні паветранага руху «Белаэранавігацыя»',
    'company_address': 'г. Мінск, вул. Караткевіча, 19',
    'phone': 'Тэлефон',
    'fax': 'факс',
    'go_back': 'Вярнуцца назад',
    
    // Адмін панэль
    'user_management': 'Кіраванне карыстальнікамі',
    'role_management': 'Кіраванне ролямі',
    'news_management': 'Кіраванне навінамі',
    'category_management': 'Кіраванне катэгорыямі',
    'branch_management': 'Кіраванне філіяламі',
    'vacancy_management': 'Кіраванне вакансіямі',
    'management_management': 'Кіраванне кіраўніцтвам',
    'management_title': 'КІРАЎНІЦТВА ДЗЯРЖАЎНАГА ПРАДПРЫЕМСТВА «БЕЛАЭРАНАВІГАЦЫЯ»',
    'loading_managers': 'Загрузка інфармацыі пра кіраўніцтва...',
    'no_managers_info': 'Інфармацыя пра кіраўніцтва адсутнічае',
    'data_will_be_added': 'Даныя будуць дададзены ў бліжэйшы час',
    'book_appointment': 'Запісацца на прыём',
    'hide_booking': 'Схаваць запіс',
    'booking_appointment': 'Запіс на прыём',
    'fill_booking_form': 'Запоўніце форму для запісу на прыём да кіраўніка',
    'selected_time': 'Выбраны час',
    'full_name': 'ПІБ',
    'enter_full_name': 'Увядзіце ваша поўнае імя',
    'enter_email': 'Увядзіце ваш email',
    'additional_info': 'Дадатковая інфармацыя',
    'describe_visit_purpose': 'Апішыце мэту візіту (неабавязкова)',
    'book': 'Запісацца',
    'booking_success': 'Запіс на прыём паспяхова аформлены!',
    'booking_error': 'Памылка пры запісе на прыём',
    'fill_required_fields': 'Запоўніце ўсе абавязковыя палі',
    'booking_slots': 'Слоты для запісу',
    'loading_schedule': 'Загрузка раскладу...',
    'booked': 'Занята',
    'unavailable': 'Недаступна',
    'no_available_slots': 'Няма даступных слотаў для запісу',
    'contact_administrator': 'Звярніцеся да адміністратара для налады раскладу',
    'reception_schedule': 'Расклад прыёму',
    'offices': 'Кабінеты',
    
    // Дадаткова
    'loading': 'Загрузка...',
    'error': 'Памылка',
    'no_data': 'Няма даных',
    'read_more': 'Чытаць далей',
    'back': 'Назад',
    'save': 'Захаваць',
    'cancel': 'Адмена',
    'delete': 'Выдаліць',
    'edit': 'Рэдагаваць',
    'add': 'Дадаць',
    'close': 'Зачыніць',
    'showing': 'Паказана',
    'of': 'з',
    'to_top': 'Да пачатку спісу',
    
    // Меню і навігацыя
    'appeals': 'Звароты',
    'social_ideological_work': 'Сацыяльная і ідэалагічная работа',
    'electronic_appeals': 'Электронныя звароты',
    'voluntary_report': 'Добраахвотнае паведамленне аб небяспечнай падзеі',
    'appeal_methods': 'Спосабы падачы зваротаў і парадак разгляду',
    'reception_schedules': 'Графікі прыёму',
    'consumer_questionnaire': 'Анкета спажыўца аэранавігацыйных паслуг',
    'united_trade_union': 'Аб\'яднаная прафсаюзная арганізацыя',
    'white_rus': 'Белая Русь',
    'brsm': 'БРСМ',
    'belarusian_women_union': 'Беларускі саюз жанчын',
    'healthy_lifestyle': 'За здаровы лад жыцця',
    'improvement_year': 'Год аблашчэння',
    'memory_pain': 'Памяць і боль беларускай зямлі',
    'version_visually_impaired': 'Версія для слабавідучых',
    'accessibility_settings': 'Налады даступнасці',
    'accessibility_mode': 'Рэжым даступнасці',
    'enable_visually_impaired': 'Уключыць версію для слабавідучых',
    'accessibility_mode_description': 'Уключае спецыяльныя налады для паляпшэння даступнасці сайта',
    'text_settings': 'Налады тэксту',
    'font_size': 'Памер шрыфта',
    'font_size_recommendation': 'Рэкамендуецца павелічэнне да 200% для слабавідучых',
    'line_spacing': 'Міжрадковы інтэрвал',
    'line_spacing_recommendation': 'Рэкамендуецца 1.5x для лепшай чытальнасці',
    'letter_spacing': 'Міжлітарны інтэрвал',
    'letter_spacing_recommendation': 'Павелічэнне інтэрвалу паміж літарамі для лепшай чытальнасці',
    'font_family': 'Сямейства шрыфтоў',
    'standard_font': 'Стандартны шрыфт',
    'arial_font': 'Arial',
    'arial_recommendation': 'Arial рэкамендуецца для лепшай чытальнасці',
    'colors_contrast': 'Колеры і кантраснасць',
    'contrast': 'Кантраснасць',
    'normal_contrast': 'Звычайная',
    'high_contrast': 'Высокая (7:1)',
    'color_scheme': 'Каляровая схема',
    'dark_scheme': 'Цёмная',
    'inverted_scheme': 'Інвертаваная',
    'color_scheme_description': 'Дазваляе выбраць зручную каляровую схему',
    'additional_settings': 'Дадатковыя налады',
    'reduce_motion': 'Паменшыць анімацыі',
    'reduce_motion_description': 'Адключае анімацыі для карыстальнікаў з вестыбулярнымі расстройствамі',
    'show_focus': 'Падсветка фокуса',
    'show_focus_description': 'Выразна паказвае элемент у фокусе для навігацыі з клавіятуры',
    'reset': 'Скінуць',
    'apply_settings': 'Прымяніць',
    
    // Загалоўкі блокаў
    'left_upper_block': 'Левы верхні блок',
    'left_middle_block': 'Левы сярэдні блок',
    'left_lower_block': 'Левы ніжні блок',
    
    // Назва прадпрыемства
    'company_full_name': 'Рэспубліканскае унітарнае прадпрыемства па аэранавігацыйным абслугоўванні паветранага руху «Белаэранавігацыя»',
    
    // Асабісты кабінет
    'profile': 'Асабісты кабінет',
    'personal_info': 'Асабістая інфармацыя',
    'account_settings': 'Налады аккаунта',
    'security': 'Бяспека',
    'profile_completeness': 'Запоўненасць профілю',
    'registration_date': 'Рэгістрацыя',
    'last_login': 'Апошні ўваход',
    'email_verified': 'Пацверджаны',
    'email_not_verified': 'Не пацверджаны',
    'account_active': 'Актыўны',
    'account_blocked': 'Заблакіраваны',
    'change_password': 'Змяніць пароль',
    'current_password': 'Бягучы пароль',
    'new_password': 'Новы пароль',
    'confirm_password': 'Пацвердзіце пароль',
    'delete_account': 'Выдаліць аккаунт',
    'delete_account_warning': 'Увага! Гэта дзеянне незваротнае. Усе вашы даныя будуць выдалены назаўсёды.',
    'confirm_password_delete': 'Пацвердзіце паролем',
    'male': 'Мужчынскі',
    'female': 'Жаночы',
    'other': 'Іншы',
    'choose_gender': 'Выберыце пол',
    'about_me': 'Пра сябе',
    'first_name': 'Імя',
    'last_name': 'Прозвішча',
    'middle_name': 'Імя па бацьку',
    'phone': 'Тэлефон',
    'date_of_birth': 'Дата нараджэння',
    'gender': 'Пол',
    'address': 'Адрас',
    'position': 'Пасада',
    'department': 'Аддзел',
    'enter_first_name': 'Увядзіце імя',
    'enter_last_name': 'Увядзіце прозвішча',
    'enter_middle_name': 'Увядзіце імя па бацьку',
    'enter_address': 'Увядзіце адрас',
    'enter_position': 'Увядзіце пасаду',
    'enter_department': 'Увядзіце аддзел',
    'tell_about_yourself': 'Раскажыце пра сябе...',
    'profile_updated_successfully': 'Профіль паспяхова абноўлены',
    'error_updating_profile': 'Памылка пры абнаўленні профілю',
    'passwords_do_not_match': 'Паролі не супадаюць',
    'password_min_length': 'Новы пароль павінен змяшчаць мінімум 6 сімвалаў',
    'password_changed_successfully': 'Пароль паспяхова зменены',
    'error_changing_password': 'Памылка пры змене пароля',
    'password_info': 'Інфармацыя пра пароль',
    'last_password_change': 'Апошняя змена пароля',
    'password_expired': 'Пароль скончыўся. Патрабуецца змена пароля.',
    'password_expires_soon': 'Пароль трэба будзе змяніць праз {days}',
    'password_expires_in': 'Пароль трэба будзе змяніць праз {days}',
    'password_never_changed': 'Пароль ніколі не мяняўся',
    'password_required': 'Пароль абавязковы',
    'force_password_change_title': 'Патрабуецца змена пароля',
    'force_password_change_description': 'Для бяспекі вашага акаўнта неабходна змяніць пароль пры першым уваходзе.',
    'account_deleted_successfully': 'Аккаунт паспяхова выдалены',
    'error_deleting_account': 'Памылка пры выдаленні аккаунта',
    'loading_profile': 'Загрузка профілю...',
    'error_loading_profile': 'Памылка загрузкі профілю',
    'try_again': 'Паспрабаваць зноў',
    'try_refresh_page': 'Паспрабуйце абнавіць старонку',
    'profile_not_found': 'Профіль не знойдзены',
    'not_authorized_error': 'Магчыма, вы не аўтарызаваны або адбылася памылка',
    'manage_profile_settings': 'Кіруйце сваім профілем і наладамі',
    'saving': 'Захаванне...',
    'save_changes': 'Захаваць змены',
    'password': 'Пароль',
    'change_password_description': 'Змяніце свой пароль',
    'changing_password': 'Змена пароля',
    'change_password_description_modal': 'Увядзіце бягучы пароль і новы пароль для змены.',
    'enter_current_password': 'Увядзіце бягучы пароль',
    'enter_new_password': 'Увядзіце новы пароль',
    'confirm_new_password': 'Пацвердзіце новы пароль',
    'changing': 'Змена...',
    'delete_account_irreversible': 'Гэта дзеянне незваротнае',
    'delete_account_title': 'Выдаленне аккаунта',
    'delete_account_description': 'Гэта дзеянне незваротнае. Пацвердзіце паролем для выдалення аккаунта.',
    'delete_account_warning_text': 'Увага! Гэта дзеянне незваротнае. Усе вашы даныя будуць выдалены назаўсёды.',
    'enter_password_confirmation': 'Увядзіце пароль для пацвярджэння',
    'deleting': 'Выдаленне...',
    'role': 'Роля',
    
    // Пошук
    'search_results': 'Вынікі пошуку',
    'search_query': 'Па запыце',
    'search_found': 'знойдзена',
    'search_results_count': 'вынікаў',
    'search_no_results': 'Нічога не знойдзена',
    'search_no_results_desc': 'Па вашым запыце нічога не знойдзена. Паспрабуйце змяніць пошукавы запыт.',
    'search_min_chars': 'Увядзіце пошукавы запыт (мінімум 2 сімвалы)',
    'search_loading': 'Пошук...',
    'search_error': 'Памылка пошуку',
    'search_error_desc': 'Адбылася памылка пры выкананні пошуку. Паспрабуйце пазней.',
    
    // Навіны
    'create_news': 'Стварыць навіну',
    'edit_news': 'Рэдагаваць',
    'creating_news': 'Стварэнне навіны',
    'editing_news': 'Рэдагаванне навіны',
    'title': 'Загаловак',
    'content': 'Змест',
    'category_id': 'ID катэгорыі',
    'file_selected': 'Файл выбраны',
    'creating': 'Стварэнне...',
    'create': 'Стварыць',
    'updating': 'Абнаўленне...',
    'update': 'Абнавіць',
    'news_created_successfully': 'Навіна паспяхова створана!',
    'error_creating_news': 'Памылка пры стварэнні навіны',
    'news_updated_successfully': 'Навіна паспяхова абноўлена!',
    'error_updating_news': 'Памылка пры абнаўленні навіны',
    'confirm_delete_news': 'Вы ўпэўнены, што хочаце выдаліць навіну',
    'news_deleted_successfully': 'Навіна паспяхова выдалена!',
    'error_deleting_news': 'Памылка пры выдаленні навіны',
    'error_loading_news': 'Памылка пры загрузцы навін',
    'no_news_yet': 'Навін пакуль няма',
    'create_first_news': 'Стварыце першую навіну, націснуўшы на кнопку вышэй',
    'current_image': 'Бягучая выява',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      // Получаем язык из localStorage только если разрешены функциональные куки
      if (canUseFunctional()) {
        const savedLanguage = localStorage.getItem('language') as Language;
        return savedLanguage && ['ru', 'en', 'be'].includes(savedLanguage) ? savedLanguage : 'ru';
      }
      return 'ru';
    } catch (error) {
      // Если произошла ошибка при инициализации, возвращаем язык по умолчанию
      console.warn('Error initializing language:', error);
      return 'ru';
    }
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    
    // Сохраняем в localStorage только если разрешены функциональные куки
    if (canUseFunctional()) {
      localStorage.setItem('language', lang);
    }
    
    // Обновляем HTML lang атрибут и отключаем авто-перевод
    document.documentElement.lang = lang;
    document.documentElement.setAttribute('translate', 'no');
  };

  const t = (key: string): string => {
    const translation = translations[language][key];
    return translation || key; // Возвращаем ключ, если перевод не найден
  };

  // Устанавливаем язык при загрузке и отключаем авто-перевод
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.setAttribute('translate', 'no');
    
    // Дополнительно отключаем авто-перевод для Google Chrome
    const metaGoogle = document.querySelector('meta[name="google"]');
    if (!metaGoogle) {
      const meta = document.createElement('meta');
      meta.name = 'google';
      meta.content = 'notranslate';
      document.head.appendChild(meta);
    }
  }, [language]);

  const contextValue = React.useMemo(() => ({
    language,
    setLanguage,
    t
  }), [language]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Возвращаем значения по умолчанию вместо выброса ошибки для лучшего UX
    console.warn('useLanguage called outside LanguageProvider, using default values');
    return {
      language: 'ru' as Language,
      setLanguage: () => {},
      t: (key: string) => key
    };
  }
  return context;
};
